---
theme: jekyll-theme-cayman
title: 'Moment-of-truth'
page_title: 'this appears for og'
headline: 'testing headline'
description: 'testing description'
logo: '/assets/imgs/favicon.ico'
defaults:
  - scope:
      path: ''
    values:
      image: 'assets/imgs/og-dp.jpg'
      width: 1200
      height: 630
exclude:
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE
---

# For reference, Jekyll SEO Tag:
# https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html
