name: Auto-commenter

on:
  pull_request:
    branches: [main]
    types: [closed]  

permissions:
  id-token: write
  issues: write
  pull-requests: write

jobs:
  automated-message:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # pullRequestClosed: >
          #   👋 @{{ author }} This PR is closed.

          pullRequestMerged: |
            "Hi @{{ author }},

            It looks like your issue has been transferred to the Consul on Kubernetes repository.
            If your issue is a question or bug report, there is some additional context that will
            help us solve your issue. Please reply with the following information if it is not
            included in your original issue:

            - the [Helm values](https://www.consul.io/docs/k8s/helm) you used to install Consul
            on Kubernetes
            - the version of Consul on Kubernetes used
            - the version of Kubernetes you are using
            - if you installed Consul on Kubernetes using Helm or the Consul-K8s CLI"
