name: Auto-commenter

on:
  pull_request:
    branches: [main]
    types: [closed]  

permissions:
  id-token: write
  issues: write
  pull-requests: write

jobs:
  automated-message:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # pullRequestClosed: >
          #   👋 @{{ author }} This PR is closed.

          pullRequestMerged: "Thank you for contributing @{{{ author }}, Makes sure to check your contributions [here](https://iamwatchdogs.github.io/moment-of-truth/)."
