name: c-cpp-linter

on:
  pull_request:
    branches: [main]
    paths: ['**.c', '**.cpp']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4.1.0

      - name: clang-format
        uses: egor-tensin/clang-format@v1
        
      - uses: cpp-linter/cpp-linter-action@v2.6.1
        id: linter
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''
          thread-comments: true
          step-summary: true
          
      # - name: clang-format-12 -style=Google path/to/filename.x
      #   run: |
      #     clang-format-12 -style=Google c-cpp-test/should-not-pass.c
      #     clang-format-12 -style=Google c-cpp-test/test.c
          
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
          echo "No. of checks failed: ${{ steps.linter.outputs.checks-failed }}"
          exit 1
