name: c-cpp-linter

on:
  pull_request:
    branches: [main]
    paths: ['**.c', '**.cpp']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4.1.0
        
      - uses: cpp-linter/cpp-linter-action@v2.6.1
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          thread-comments: true
          step-summary: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
          exit 1
