name: javascript-linter

on:
  pull_request:
    branches: [main]
    paths: ['**.js', '**.jsx', '**.ts', '**.tsx']

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repo
      uses: actions/checkout@v4.1.0

    - name: install node
      uses: actions/setup-node@v3.8.1

    - name: install ESLint
      run: | 
        npm init -y
        npm install eslint

    - name: ESLint Annotate
      uses: a-b-r-o-w-n/eslint-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: ESLint Action eslintrc
      uses: mrdivyansh/eslint-action@v1.0.7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
