name: javascript-linter

on:
  pull_request:
    branches: [main]
    paths: ['**.js', '**.jsx', '**.ts', '**.tsx']

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repo
      uses: actions/checkout@v4.1.0

    # - name: install node v12
    #   uses: actions/setup-node@v3.8.1
    #   with:
    #     node-version: 12

    - name: eslint action
      uses: a-b-r-o-w-n/eslint-action@v2.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: eslint
      uses: bradennapier/eslint-plus-action@v3
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      with: 
        issueSummaryType: full
