name: Lint Python Code

on:
  pull_request:
    branches: [main]
    paths: ['*.py']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.12
    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7
