name: Testing-Manual

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: launch manual workflow-super linter
      uses: ./.github/workflows/manual.yml
