name: Testing-Manual

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0

  lint:
    needs: [checkout]
    uses: ./.github/workflows/manual.yml
