name: python-linter

on:
  pull_request:
    branches: [main]
    paths: ['**.py']

jobs:
  python-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repo
      uses: actions/checkout@v4.1.0

    - name: Setting up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.12

    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7
